### ISSUE TITLE
Issue when instantiating new Response with array data

### ISSUE THREAD

**Issue by dextercampos** [loyaltycorp/externals#78]
In https://github.com/loyaltycorp/externals/blob/0616b622869a2d826ce8c6fb832bd6137a11a648/src/HttpClient/Response.php#L113

When doing something like this:
```
new \EoneoPay\Externals\HttpClient\Response(new \GuzzleHttp\Psr7\Response(), [
    'key1' => ['value-1']
])
```
`EoneoPay\Utils\Collection` will execute a `new static(['value-1'])` from the `$data` which will then throw an error since `new static(['value-1'])` will be equivalent to `new \EoneoPay\Externals\HttpClient\Response(['value-1'])`. This will throw an error since it's expecting a `Psr Response` but an array is given..

`EoneoPay\Utils\Collection` reference:
https://github.com/loyaltycorp/utils/blob/32b0c0ce70edddf7a1ce08fee441a1b4eca1823d/src/Collection.php#L249

**Comment by merk** [comment]
We've removed the Collection implementation from the Response. To replicate this functionality you'll need to parse the Response content in another service and create a Collection directly.
